# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: check-yaml
        args: ['--unsafe']
      - id: check-ast
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
    - id: isort
      name: isort
      args: [-p=nervosum, --profile=black]
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=79]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear==20.1.4"]
  - repo: https://github.com/terrencepreilly/darglint
    rev: master
    hooks:
     - id: darglint
       args: [--docstring-style=google, --strictness=short]
